# Generated by Django 5.2.5 on 2025-08-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'draft'), (1, 'Published')], default=1),
        ),
    ]
