# Generated by Django 5.2.5 on 2025-08-14 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_husband_m_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['-time_created'], 'verbose_name': 'Popular women', 'verbose_name_plural': 'Popular womens'},
        ),
        migrations.AlterField(
            model_name='women',
            name='husband',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wife', to='main.husband'),
        ),
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=True),
        ),
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
